- name: Destroy cluster before starting again
  command: kubeadm reset -f
  # iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
  # rm -r ~/.kube/

- name: Initialize k8s cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_init_output

- name: Create file with output
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /root/kubeadminit

- name: Prepare kubejoin script
  shell: tail -2 /root/kubeadminit > /root/kubejoin.sh

- name: Get kubejoin
  fetch:
    dest: ./join
    src: /root/kubejoin.sh

- name: Organize files
  shell: |
      cp join/{{ inventory_hostname }}/root/kubejoin.sh join/  
      rm -fr join/{{ inventory_hostname }}
  delegate_to: localhost
  become: no




# - name: Install pod network
#   tags: debug
#   shell: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
#   environment:
#     KUBECONFIG: "/etc/kubernetes/admin.conf"